# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    MailNotificationGenerator:
        class: AppBundle\Service\MailNotificationGenerator
        arguments: 
            - '@mailer'
            - '@templating'

    AlertNotificationGenerator:
        class: AppBundle\Service\AlertNotificationGenerator
        arguments: 
            - '@templating'
            - '@doctrine.orm.default_entity_manager'

    ContactMailGenerator:
        class: AppBundle\Service\ContactMailGenerator
        arguments: 
            - '@mailer'
            - '@doctrine.orm.default_entity_manager'

