AppBundle\Entity\Categorias:
    type: entity
    table: categorias
    indexes:
        idPadre:
            columns:
                - idPadre
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
    manyToOne:
        idpadre:
            targetEntity: Categorias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idPadre:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
