AppBundle\Entity\Message:
    type: entity
    table: message
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        subject:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        body:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks: {  }
