AppBundle\Entity\Messagemetadata:
    type: entity
    table: messagemetadata
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isRead:
            type: boolean
            nullable: false
            column: is_read
    lifecycleCallbacks: {  }
