AppBundle\Entity\Tiposoferta:
    type: entity
    table: tiposoferta
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    lifecycleCallbacks: {  }
